# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sree Ganesh Balasubramani
email: sreeganb@uci.edu        
description: > # this means to ignore newlines until "baseurl:"
  Sree is a grad school at UC Irvine in Prof. Filipp Furche's 
  research group. He works on cool stuff such as time-dependent
  random phase approximation. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  sreeganb

# Build settings
markdown: kramdown
