# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sree Ganesh Balasubramani
email: sreeganb@uci.edu
description: > # this means to ignore newlines until "baseurl:"
  Theoretical Chemistry: Electronic structure method development and applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  sreeganb

# Build settings
markdown: kramdown
theme: minimal
exclude:
  - Gemfile
  - Gemfile.lock
# remote_theme: mmistakes/minimal-mistakes

#where things are

source: .
destination: ./_site
layouts: ./_layouts
data_source: ./_data
collections: null

#Handling Reading

safe: false
include: [".htaccess"]
exclude: []
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion

highlighter: rouge
lsi: false
excerpt_separator: "\n\n"

redcarpet: 
    extensions: []
include: ['_pages']
coderay: 
    coderay_wrap: div
    coderay_line_numbers: inline 
    coderay_bold_every: 10
    coderay_css: style
    coderay_tab_width: 4
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-polyglot
  - jekyll-seo-tag
style:
  body: 'white'
  margin: 0%
  padding: 20%
  nav: "#222"
  articles: 'stripe' # 'light' 'dark' and 'stripe' possible
  uppercase: true
paginate: 10  
