# theme: "jekyll-theme-clean-blog"

title: Sree Ganesh Balasubramani
email: sreeganb@uci.edu
description: > # this means to ignore newlines until "baseurl:"
   Electronic structure theory and applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sreeganb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: turbomoler
github_username:  sreeganb

# Build settings
markdown: kramdown

# Build settings
markdown:           kramdown
mathjax:            true
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

#where things are

source: .
destination: ./_site
layouts: ./_layouts
data_source: ./_data
collections: null

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
