title: Sree Ganesh Balasubramani
email: sreeganb@uci.edu
description: > # this means to ignore newlines until "baseurl:"
   Electronic structure theory and applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sreeganb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: turbomoler
github_username:  sreeganb

# Build settings
markdown: kramdown
mathjax: true

# remote_theme: mmistakes/minimal-mistakes

#where things are

source: .
destination: ./_site
layouts: ./_layouts
data_source: ./_data
collections: null

#Handling Reading

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


theme: jekyll-theme-minimal
