# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sree Ganesh Balasubramani
email: sreeganb@uci.edu        
description: > # this means to ignore newlines until "baseurl:"
  This site will possibly provide some useful discussions and 
  Sree's perspectives on quantum chemistry (density functional theory
  in particular) as he learns to navigate through the deep and unfriendly
  bottomless abyss that is graduate school. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sreeganb.github.io" # the base hostname & protocol for your site
github_username:  sreeganb

# Build settings
markdown: kramdown
